language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5 
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-dev -qq
    - wget http://downloads.sourceforge.net/project/ssdeep/ssdeep-2.13/ssdeep-2.13.tar.gz
    - tar -zxvf ssdeep-2.13.tar.gz
    - cd ssdeep-2.13
    - ./configure && make
    - sudo make install
    - sudo ldconfig
    - cd ..
install:
    - python setup.py build
    - python setup.py install
before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - cd tests
script:
    - python test.py
